<?php
class ISC_QUOTE_EXCEPTION extends Exception
{
	const ERROR_NO_STOCK = 1;

	const COUPON_INVALID = 2001;
	const COUPON_DISABLED = 2002;
	const COUPON_EXPIRED_TIME = 2003;
	const COUPON_EXPIRED_USES = 2004;
	const COUPON_MIN_PURCHASE = 2005;
	const COUPON_DOES_NOT_APPLY = 2006;
	const COUPON_LOCATION_DOES_NOT_APPLY = 2007;
	const COUPON_METHOD_DOES_NOT_APPLY = 2008;
	const COUPON_LOCATION_DOES_NOT_SPECIFIED = 2009;
	const COUPON_METHOD_DOES_NOT_SPECIFIED = 2010;
}